module.exports = {
    env: {
        es6: true,
    },
    parserOptions: {
        ecmaVersion: 2018,
    },
    extends: 'eslint:recommended',
    rules: {
        'indent': ['error', 4],
        'linebreak-style': ['error', 'unix'],
        'max-len': ['error', { 'code': 120 }],
        'quotes': ['error', 'single'],
        'eqeqeq': 'error',
        'no-multi-spaces': 'error',
        'no-trailing-spaces': 'error',
        'semi-spacing': 'error',
        'key-spacing': 'error',
        'arrow-spacing': 'error',
        'arrow-parens': 'error',
        'space-in-parens': 'error',
        'comma-spacing': 'error',
        'space-infix-ops': 'error',
        'no-unused-vars': ['error', { 'argsIgnorePattern': '^_' }],
        'keyword-spacing': 'error',
        'func-call-spacing': 'error',
        'space-before-function-paren': ['error', { 'anonymous': 'always', 'named': 'never', 'asyncArrow': 'always' }],
        'object-curly-spacing': ['error', 'always'],
        'array-bracket-spacing': ['error', 'never'],
        'semi': ['error', 'always'],
        'comma-dangle': ['error', 'always-multiline'],
        'no-var': 'error',
        'prefer-const': 'error',
        'no-use-before-define': ['error', { 'functions': false }],
    },
};
